{% set name = "sparse" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparse-{{ version }}.tar.gz
  sha256: b69fa20716af820c4ddba874ca59322054c77c18a3ba761d7d4d774e7eab339f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - numpy >=1.17
    - scipy >=0.19
    - numba >=0.49

test:
  imports:
    - sparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydata/sparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse multi-dimensional arrays for the PyData ecosystem

  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org/en/{{ version }}/
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
