# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: sparse
  version: 0.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/sparse-${{ version }}.tar.gz
  sha256: e7961a81592e0372a21023fcb29e651787b03ac66e3fd6df81772d3d70dc25a5

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6,<3.10
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.6,<3.10
    - numpy >=1.13,<2
    - scipy >=0.19

tests:
  - python:
      imports:
        - sparse
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Sparse multi-dimensional arrays for the PyData ecosystem
  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  homepage: https://github.com/pydata/sparse
  repository: https://github.com/pydata/sparse
  documentation: https://sparse.pydata.org/en/${{ version }}/

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
